[workspace]
members = ["common", "bastion-server"]

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tempfile = "3.10"
ephemwork-common = { path = "common" }

[package]
name = "ephemwork"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde = { workspace = true }
toml = "0.8"
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
aws-config = "1.5"
aws-sdk-ec2 = "1.65"
aws-sdk-ssm = "1.65"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
serde_json = { workspace = true }
ssh2 = "0.9"
url = "2.5"
ephemwork-common = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
