//! Render the bastion's nginx config from a registry snapshot, and reload
//! nginx after every change so newly-registered sessions become routable
//! immediately.
//!
//! Routing strategy: `X-Ephemwork: <user>:<service>` looks up a `host:port`
//! string via an `nginx map`, and `proxy_pass` forwards there. A missing
//! mapping returns 404 so the laptop CLI sees a clean error instead of a
//! mysterious connection drop.

use crate::handlers::MutationListener;
use crate::registry::{Key, Registry};
use anyhow::{anyhow, Context, Result};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// nginx config the bastion will write whenever the registry changes.
/// Pure function; no I/O so tests can pin the wire format precisely.
pub fn render_config(entries: &[(Key, u16)]) -> Result<String> {
    for (key, _) in entries {
        if !is_safe_identifier(&key.user) {
            return Err(anyhow!(
                "unsafe characters in user identifier: {:?}",
                key.user
            ));
        }
        if !is_safe_identifier(&key.service) {
            return Err(anyhow!(
                "unsafe characters in service identifier: {:?}",
                key.service
            ));
        }
    }

    let mut out = String::new();
    out.push_str("# Generated by ephemwork bastion control plane. DO NOT EDIT BY HAND.\n");
    out.push_str("# Re-rendered after every register/deregister.\n\n");
    out.push_str("resolver 127.0.0.1 valid=300s ipv6=off;\n\n");
    out.push_str("map $http_x_ephemwork $ephem_target {\n");
    out.push_str("    default \"\";\n");
    for (key, port) in entries {
        out.push_str(&format!(
            "    \"{user}:{service}\" \"127.0.0.1:{port}\";\n",
            user = key.user,
            service = key.service,
            port = port
        ));
    }
    out.push_str("}\n\n");
    out.push_str("server {\n");
    out.push_str("    listen 80 default_server;\n");
    out.push_str("    listen [::]:80 default_server;\n\n");
    out.push_str("    location = /ephemwork-health {\n");
    out.push_str("        return 200 \"ok\\n\";\n");
    out.push_str("    }\n\n");
    out.push_str("    location / {\n");
    out.push_str("        if ($ephem_target = \"\") {\n");
    out.push_str("            return 404 \"no active ephemwork session for this header\\n\";\n");
    out.push_str("        }\n");
    out.push_str("        proxy_pass http://$ephem_target;\n");
    out.push_str("        proxy_http_version 1.1;\n");
    out.push_str("        proxy_set_header Host $host;\n");
    out.push_str("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n");
    out.push_str("        proxy_set_header X-Forwarded-Proto $scheme;\n");
    out.push_str("        proxy_set_header X-Ephemwork $http_x_ephemwork;\n");
    out.push_str("        proxy_read_timeout 300s;\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    Ok(out)
}

/// Identifiers must be ASCII alnum or one of `_-.`. This keeps the config
/// trivial to render (no escaping) and ensures the header value is the
/// same one nginx sees over the wire.
pub fn is_safe_identifier(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    s.bytes().all(|b| {
        b.is_ascii_alphanumeric() || b == b'_' || b == b'-' || b == b'.'
    })
}

/// `MutationListener` that re-renders the nginx config after every
/// registry change and asks nginx to reload. Reload failures are logged
/// loudly because they mean the new mapping is *not* live yet.
pub struct NginxReloader {
    pub config_path: PathBuf,
    pub reload_command: ReloadCommand,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReloadCommand {
    /// `nginx -s reload`
    NginxBinary,
    /// Skip the reload (used in tests and dry runs).
    None,
    /// Custom shell command (`sh -c <cmd>`); useful for systemd-managed nginx.
    Custom(String),
}

impl NginxReloader {
    pub fn new(config_path: PathBuf, reload_command: ReloadCommand) -> Self {
        Self {
            config_path,
            reload_command,
        }
    }

    pub fn write_config(&self, contents: &str) -> Result<()> {
        if let Some(parent) = self.config_path.parent() {
            if !parent.as_os_str().is_empty() {
                std::fs::create_dir_all(parent)
                    .with_context(|| format!("creating {}", parent.display()))?;
            }
        }
        let tmp = self.config_path.with_extension("conf.tmp");
        std::fs::write(&tmp, contents)
            .with_context(|| format!("writing {}", tmp.display()))?;
        std::fs::rename(&tmp, &self.config_path).with_context(|| {
            format!(
                "renaming {} -> {}",
                tmp.display(),
                self.config_path.display()
            )
        })?;
        Ok(())
    }

    pub fn reload(&self) -> Result<()> {
        match &self.reload_command {
            ReloadCommand::None => Ok(()),
            ReloadCommand::NginxBinary => run_status(Command::new("nginx").arg("-s").arg("reload")),
            ReloadCommand::Custom(cmd) => {
                run_status(Command::new("sh").arg("-c").arg(cmd))
            }
        }
    }
}

fn run_status(command: &mut Command) -> Result<()> {
    let status = command
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .status()
        .context("spawning reload command")?;
    if !status.success() {
        return Err(anyhow!("reload command exited {:?}", status.code()));
    }
    Ok(())
}

impl MutationListener for NginxReloader {
    fn on_change(&mut self, registry: &Registry) {
        let snap = registry.snapshot();
        let rendered = match render_config(&snap) {
            Ok(s) => s,
            Err(e) => {
                tracing::error!(?e, "rendering nginx config failed; skipping reload");
                return;
            }
        };
        if let Err(e) = self.write_config(&rendered) {
            tracing::error!(?e, path = %self.config_path.display(), "writing nginx config failed");
            return;
        }
        if let Err(e) = self.reload() {
            tracing::error!(?e, "nginx reload failed; new mapping is not live yet");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::{PortRange, Registry};
    use tempfile::tempdir;

    fn entry(user: &str, service: &str, port: u16) -> (Key, u16) {
        (Key::new(user, service), port)
    }

    #[test]
    fn empty_config_returns_404_block() {
        let s = render_config(&[]).unwrap();
        assert!(s.contains("default \"\""));
        assert!(s.contains("no active ephemwork session"));
        assert!(s.contains("location = /ephemwork-health"));
    }

    #[test]
    fn single_entry_emits_map_line() {
        let s = render_config(&[entry("alice", "api", 10_000)]).unwrap();
        assert!(s.contains("\"alice:api\" \"127.0.0.1:10000\""));
    }

    #[test]
    fn multiple_entries_emit_in_order() {
        let s = render_config(&[
            entry("alice", "api", 10_000),
            entry("bob", "worker", 10_001),
        ])
        .unwrap();
        let alice_pos = s.find("alice:api").unwrap();
        let bob_pos = s.find("bob:worker").unwrap();
        assert!(alice_pos < bob_pos, "snapshot order should be preserved");
    }

    #[test]
    fn render_includes_routing_header_propagation() {
        let s = render_config(&[]).unwrap();
        assert!(s.contains("proxy_set_header X-Ephemwork $http_x_ephemwork"));
    }

    #[test]
    fn render_rejects_quote_in_user() {
        let bad = (Key::new("alice\"bad", "api"), 10_000);
        let err = render_config(&[bad]).unwrap_err().to_string();
        assert!(err.contains("user"), "got: {err}");
    }

    #[test]
    fn render_rejects_newline_in_service() {
        let bad = (Key::new("alice", "api\nworker"), 10_000);
        let err = render_config(&[bad]).unwrap_err().to_string();
        assert!(err.contains("service"), "got: {err}");
    }

    #[test]
    fn render_rejects_empty_user() {
        let bad = (Key::new("", "api"), 10_000);
        assert!(render_config(&[bad]).is_err());
    }

    #[test]
    fn safe_identifier_accepts_dotted_names() {
        assert!(is_safe_identifier("alice.smith"));
        assert!(is_safe_identifier("api-v2"));
        assert!(is_safe_identifier("worker_1"));
        assert!(is_safe_identifier("0day"));
    }

    #[test]
    fn safe_identifier_rejects_special_chars() {
        for bad in ["space here", "semi;colon", "quo\"te", "back\\slash", "lf\nfeed", "$var"] {
            assert!(!is_safe_identifier(bad), "should reject {bad:?}");
        }
    }

    #[test]
    fn write_config_creates_parent_directory() {
        let dir = tempdir().unwrap();
        let cfg = dir.path().join("nested/deep/ephemwork.conf");
        let r = NginxReloader::new(cfg.clone(), ReloadCommand::None);
        r.write_config("contents").unwrap();
        assert_eq!(std::fs::read_to_string(&cfg).unwrap(), "contents");
    }

    #[test]
    fn reload_none_is_a_no_op() {
        let dir = tempdir().unwrap();
        let r = NginxReloader::new(dir.path().join("x.conf"), ReloadCommand::None);
        r.reload().unwrap();
    }

    #[test]
    fn reload_custom_runs_shell_command() {
        let dir = tempdir().unwrap();
        let marker = dir.path().join("touched");
        let cmd = format!("touch {}", marker.to_str().unwrap());
        let r = NginxReloader::new(
            dir.path().join("nginx.conf"),
            ReloadCommand::Custom(cmd),
        );
        r.reload().unwrap();
        assert!(marker.exists(), "shell command should have run");
    }

    #[test]
    fn reload_custom_propagates_failure() {
        let dir = tempdir().unwrap();
        let r = NginxReloader::new(
            dir.path().join("nginx.conf"),
            ReloadCommand::Custom("exit 7".into()),
        );
        let err = r.reload().unwrap_err().to_string();
        assert!(err.contains("7"), "got: {err}");
    }

    #[test]
    fn listener_writes_config_on_change() {
        let dir = tempdir().unwrap();
        let cfg = dir.path().join("ephemwork.conf");
        let mut listener = NginxReloader::new(cfg.clone(), ReloadCommand::None);
        let mut reg = Registry::with_range(PortRange {
            start: 10_000,
            end: 10_010,
        });
        reg.register(&Key::new("alice", "api")).unwrap();

        listener.on_change(&reg);

        let written = std::fs::read_to_string(&cfg).unwrap();
        assert!(written.contains("alice:api"));
        assert!(written.contains("127.0.0.1:10000"));
    }

    #[test]
    fn listener_does_not_panic_when_render_fails() {
        // Inject an unsafe identifier directly via the registry's snapshot;
        // the listener must swallow the render error, not panic.
        let dir = tempdir().unwrap();
        let mut listener =
            NginxReloader::new(dir.path().join("ephemwork.conf"), ReloadCommand::None);
        // Construct a registry whose snapshot would fail render. Easiest: use
        // load() on a hand-crafted JSON file with bad identifiers, then call
        // on_change. The listener should log and return without panicking.
        let bad_json = r#"{"range":{"start":10000,"end":10001},"entries":{"al ice/api":10000}}"#;
        let p = dir.path().join("bad.json");
        std::fs::write(&p, bad_json).unwrap();
        let reg = Registry::load(&p).unwrap();
        listener.on_change(&reg); // should not panic
    }
}
